<font face="Georgia">

<p>Welcome to 2stepAuth Wordpress plugin. Congratulations!!! You have got the right plugin for securing your blog.</p> 
</font>
<?php
echo "<div class='updated fade' style='width:900px;'><p>". __( "<font face=\"verdana\"><p>The plugin enables 2step Authentication as follows:</p>

<p><b>A. 1st step of Authentication:</b> This step is conventional Username-password combination.</p>

<p><b>B. 2nd Step of Authentication:</b> After completing 1st step successfully, the user has to validate himself using any of 3 ways:</p>

<p><b>1. SMS Code Verification:</b><br /> SMS containing a verification code is sent to verified mobile phone. Simply enter this verification code correctly to access your
Wordpress.</p>

<p><b>2. Email Code Verification:</b><br /> Sometimes, SMS Code Verification may be disabled or may not be supported. Hence, we have provided Email Authentication feature.
You have to correctly enter the Verification code sent to your email inorder to access your blog.</p>

<p><b>3. Backup Codes:</b><br /> Backup Codes are generated by this plugin and you have to <b>save these Backup codes</b> at a safe location. During 
verification, enter one of these Backup Codes to access your Wordpress. Note that each Backup code can be used just once.</p></font>", '2step_auth' ) . "</p></div>";
?>

<font face="Georgia">
<p><b>Note:</b> 2stepAuth plugin automatically generates 6 Backup Codes at a time. The plugin will <b>stop working if the count of Backup Codes falls to 0(Zero).</b></p>
</font>
<?php
echo "<div class='updated fade' style='width:900px;'><p>". __( "<font face=\"verdana\"><p><strong>Tips to prevent yourself from being locked out:</strong></p>

<p>- Try your best to enable all 3 ways of Validation.</p>
<p>- Backup codes are your saviour. Make sure you always possess them.</p></font>", '2step_auth' ) . "</p></div>";
?>


<font face="Georgia"><p>So, 2stepAuth is ready to rock!!! Are you ready to experience 2stepAuth???</p>
<?php $url = admin_url('options-general.php?page=2stepauth&step=gui0');   ?>
<p><a href='<?php echo $url; ?>' type='submit' class='button-primary'>Yes, I am ready!!! Take me to Control Panel...</a></p></font>